### PR TITLE
Improve output by giving string nodes a better description.

### PR DESCRIPTION
**Pull request by krisselden**

### CODE REVIEW

**Comment by krisselden** [comment]
@stefanpenner I added a comment, not sure if that is what you meant

**Comment by stefanpenner** [comment]
released as v0.17.2

**Comment by Turbo87** [comment]
@stefanpenner would be great if this could be ported over to https://github.com/ember-cli/broccoli-builder too. I'd like to deprecate this repo ASAP.

**Comment by stefanpenner** [comment]
I can port it.

**Pull request merged**
